### ISSUE TITLE
failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by zjj1997zju** [yangyanli/PointCNN#148]
Hi, I run your code, but failed. When I check pointcnn_cls_modelnet_x3_l4.txt, it says

> 2019-03-07 10:01:40.397380: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-07 10:01:40.582576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-03-07 10:01:40.582606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-07 10:01:40.797216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-07 10:01:40.797253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-07 10:01:40.797260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-07 10:01:40.797473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-03-07 10:01:47.215384: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
2019-03-07 10:01:47.215450: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details
Traceback (most recent call last):
  File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[131072,8,8], b.shape=[131072,8,24], m=8, n=24, k=8, batch_size=131072
	 [[{{node xconv_1_fts_X}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](xconv_1_X_2_KK, xconv_1_nn_fts_from_pts_bn/cond/Merge-0-1-TransposeNCHWToNHWC-LayoutOptimizer)]]
	 [[{{node logits/Tensordot/Shape/_263}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_15825_logits/Tensordot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

What happened ?
Thanks in advance

**Comment by burui11087** [comment]
Hi @zjj1997zju

Please downgrade your python version to python3.5 and try it again.

Thanks!

**Comment by itxiud2015** [comment]
@zjj1997zju I had the same issue, did it solved at your side?

**Comment by sayakgis** [comment]
> Hi, I run your code, but failed. When I check pointcnn_cls_modelnet_x3_l4.txt, it says
> 
> > 2019-03-07 10:01:40.397380: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> > 2019-03-07 10:01:40.582576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> > name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
> > pciBusID: 0000:02:00.0
> > totalMemory: 10.92GiB freeMemory: 10.76GiB
> > 2019-03-07 10:01:40.582606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> > 2019-03-07 10:01:40.797216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> > 2019-03-07 10:01:40.797253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
> > 2019-03-07 10:01:40.797260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
> > 2019-03-07 10:01:40.797473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
> > 2019-03-07 10:01:47.215384: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
> > 2019-03-07 10:01:47.215450: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details
> > Traceback (most recent call last):
> > File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
> > return fn(*args)
> > File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
> > options, feed_dict, fetch_list, target_list, run_metadata)
> > File "/home/zjj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
> > run_metadata)
> > tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[131072,8,8], b.shape=[131072,8,24], m=8, n=24, k=8, batch_size=131072
> > [[{{node xconv_1_fts_X}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](xconv_1_X_2_KK, xconv_1_nn_fts_from_pts_bn/cond/Merge-0-1-TransposeNCHWToNHWC-LayoutOptimizer)]]
> > [[{{node logits/Tensordot/Shape/_263}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_15825_logits/Tensordot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> What happened ?
> Thanks in advance



> @zjj1997zju I had the same issue, did it solved at your side?

Hi, I spent a day figuring out on my new VM with single 32GB V100 card, faced the same issue. The conclusion is i downgraded Cuda toolkit to 9.2 and Cudnn to 7.6.5. 
And it worked like a charm.
